config/routes.rb
MAdeK::Application.routes.draw do

  root to: 'application#root'

  # RESTful Routes #############################################################
  # NOTE: ALL Models are 'resources', don't confuse with "MediaResources"!

  ## Concerns - used with several Resources ####################################
  concern :previewable do
    get 'preview/:size', action: :preview, as: 'preview', on: :member
  end

  ## The resources we internally call "MediaResources":
  resources :media_entries, path: 'entries', only: [:index, :show], concerns: :previewable
  resources :collections, only: [:index, :show], concerns: :previewable
  resources :filter_sets, only: [:index, :show], concerns: :previewable

  # Other App routes ###########################################################
  # TODO: resource 'users'?
  get 'my', to: 'my#dashboard', as: 'my_dashboard'

  post 'session/sign_in', to: 'sessions#sign_in'
  post 'session/sign_out', to: 'sessions#sign_out'

  # Admin routes ###############################################################
  namespace :admin do
    resources :users do
      member do
        post :switch_to
        patch :reset_usage_terms
        patch :grant_admin_role
        delete :remove_admin_role
      end
      collection do
        get :new_with_person
      end
    end
    resources :groups do
      member do
        get 'form_add_user'
        post 'add_user'
        get 'form_merge_to'
        post 'merge_to'
      end
      resources :users, only: '' do
        delete 'remove_user_from_group'
      end
    end
    resources :collections, only: [:index, :show] do
      member do
        get :media_entries
        get :collections
        get :filter_sets
      end
    end
    resources :media_entries, only: [:index, :show]
    resources :media_files, only: :show
    resources :previews, only: [:show, :destroy]
    resources :zencoder_jobs, only: :show
    resources :filter_sets, only: [:index, :show]
    root to: 'dashboard#index' 
  end

  # STYLEGUIDE #################################################################
  get 'styleguide', to: 'styleguide#index', as: 'styleguide'
  get 'styleguide/:section', to: 'styleguide#show', as: 'styleguide_section'
  get 'styleguide/:section/:element', to: 'styleguide#element', as: 'styleguide_element'

end

app/models/collection.rb
class Collection < ActiveRecord::Base

  include Concerns::EditSessions
  include Concerns::Entrust
  include Concerns::Favoritable
  include Concerns::MetaData
  include Concerns::PermissionsAssociations
  include Concerns::Users::Creator
  include Concerns::Users::Responsible

  #################################################################################

  has_many :collection_media_entry_arcs,
           class_name: Arcs::CollectionMediaEntryArc

  has_many :collection_collection_arcs,
           class_name: Arcs::CollectionCollectionArc,
           foreign_key: :parent_id

  has_many :collection_filter_set_arcs,
           class_name: Arcs::CollectionFilterSetArc

  has_many :media_entries, through: :collection_media_entry_arcs do

    def highlights
      where('collection_media_entry_arcs.highlight = ?', true)
    end

    def cover
      find_by('collection_media_entry_arcs.cover = ?', true)
    end

  end

  has_many :collections, through: :collection_collection_arcs, source: :child
  has_many :filter_sets, through: :collection_filter_set_arcs

  #################################################################################

  scope :by_title, lambda{ |title|
    joins(:meta_data).where(meta_data: { meta_key_id: 'madek:core:title' })
    .where('string ILIKE :title', title: "%#{title}%").order(:created_at, :id)
  }

  default_scope { reorder(:created_at, :id) }
end

app/models/permissions/modules/collection.rb
module Permissions
  module Modules
    module Collection
      extend ActiveSupport::Concern
      include ::Permissions::Modules::DefineDestroyIneffective
      included do
        belongs_to :collection
        belongs_to :updator, class_name: 'User'
        define_destroy_ineffective [{ get_metadata_and_previews: false,
                                      edit_metadata_and_relations: false }]
      end
    end
  end
end

app/controllers/admin/collections_controller.rb
class Admin::CollectionsController < AdminController
  before_action :find_collection, except: [:index]

  def index
    @collections = Collection.page(params[:page]).per(16)
    @collections = @collections.by_title(params[:search_terms]) \
      if params[:search_terms].present?
  end

  def show
  end

  def media_entries
    @media_entries = @collection.media_entries.page(params[:page]).per(16)
  end

  def collections
    @collections = @collection.collections.page(params[:page]).per(16)
  end

  def filter_sets
    @filter_sets = @collection.filter_sets.page(params[:page]).per(16)
  end

  private

  def find_collection
    @collection = Collection.find params[:id]
    @user = @collection.responsible_user
  end
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

  include Concerns::Filters
  include Concerns::Image

  def preview
    collection = Collection.find(params[:id])
    media_entry = \
      collection.media_entries.cover \
        or collection.media_entries.first
    get_preview_and_send_image(media_entry, params[:size])
  end

  def index
    @collections = \
      filter_by_entrusted \
      filter_by_favorite \
      filter_by_responsible \
      Collection.all
  end

  def show
    collection = Collection.find(params[:id])
    @get = ::Presenters::Collections::CollectionShow.new(collection)
  end
end

app/views/admin/collections/_action_buttons.html.haml
= link_to media_entries_admin_collection_path(collection), class: "btn btn-info #{size}" do
  = "Media entries: #{collection.media_entries.count}"
= link_to collections_admin_collection_path(collection), class: "btn btn-info #{size}" do
  = "Sets : #{collection.collections.count}"
= link_to filter_sets_admin_collection_path(collection), class: "btn btn-info #{size}" do
  = "Filter sets: #{collection.filter_sets.count}"

app/views/admin/collections/_action_panel.html.haml
.row
  .col-xs-12
    .panel.panel-default
      .panel-body
        .btn-group
          = link_to admin_user_path(user), class: 'btn btn-default' do
            %i.glyphicon.glyphicon-user
            = "User: #{user.person}"
          = render partial: 'action_buttons', locals: { collection: collection, size: nil }

app/views/admin/collections/_collection.html.haml
%tr.collection{id: collection.id}
  %th= collection.title
  %td
    = link_to admin_user_path(collection.responsible_user) do
      = collection.responsible_user.person

  %td.active.col-md-4.col-sm-6
    .btn-group
      = link_to admin_collection_path(collection), class: 'btn btn-default btn-sm' do
        %i.glyphicon.glyphicon-eye-open
      = render partial: 'action_buttons', locals: { collection: collection, size: 'btn-sm' }

app/views/admin/collections/_filter_set.html.haml
%tr.filter_set{id: filter_set.id}
  %th= filter_set.id
  %td
    = link_to admin_user_path(filter_set.responsible_user) do
      = filter_set.responsible_user.person

  %td.active
    .btn-group
      = link_to admin_filter_set_path(filter_set), class: 'btn btn-default btn-sm' do
        %i.glyphicon.glyphicon-eye-open

app/views/admin/collections/_media_entry.html.haml
%tr
  %td= media_entry.id
  %td
    = link_to admin_user_path(media_entry.responsible_user) do
      #{media_entry.responsible_user.person}

app/views/admin/collections/collections.html.haml
.page-header
  %h1
    %i.glyphicon.glyphicon-folder-open
    #{@collection.title} - Sets(#{@collections.total_count})

= render partial: 'action_panel', locals: { collection: @collection, user: @user }

.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th Title
            %th User
            %th
        %tbody
          = render partial: 'collection', collection: @collections

= paginate @collections, theme: 'admin'

app/views/admin/collections/filter_sets.html.haml
.page-header
  %h1
    %i.glyphicon.glyphicon-folder-open
    #{@collection.title} - Filter Sets(#{@filter_sets.total_count})

= render partial: 'action_panel', locals: { collection: @collection, user: @user }

.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th Id
            %th User
            %th
        %tbody
          = render partial: 'filter_set', collection: @filter_sets

= paginate @filter_sets, theme: 'admin'

app/views/admin/collections/index.html.haml
.page-header
  %h1
    %i.icon-group
    Sets (#{@collections.total_count})

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        .panel-title Search by title
      .panel-body
        = form_tag admin_collections_path, method: 'GET', class: 'form-inline'  do
          .form-group
            = text_field_tag :search_terms, params[:search_terms],
              class: 'form-control', placeholder: 'Title'
            = submit_tag 'Apply', class: 'btn btn-primary'
            = link_to 'Reset', admin_collections_path, class: 'btn btn-default'
.row
  .col-md-12
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th Title
            %th Responsible user
            %th
        %tbody
          = render partial: 'collection', collection: @collections

= paginate @collections, theme: 'admin'

app/views/admin/collections/media_entries.html.haml
.page-header
  %h1
    %i.glyphicon.glyphicon-folder-open
    #{@collection.title} - Media entries(#{@media_entries.total_count})

= render partial: 'action_panel', locals: { collection: @collection, user: @user }

.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead
          %tr
            %th Id
            %th User
        %tbody
          = render partial: 'media_entry', collection: @media_entries

= paginate @media_entries, theme: 'admin'

app/views/admin/collections/show.html.haml
.page-header
  %h1
    %i.glyphicon.glyphicon-folder-open
    #{@collection.title}

= render partial: 'action_panel', locals: { collection: @collection, user: @user }

.row
  .col-xs-12
    .table-responsive
      %table.table.table-striped
        %thead
        %tbody
        - @collection.attributes.each do |attr|
          %tr
            %td
              %strong= attr.first.humanize
            %td= attr.last